spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/compose-postgres
        username: compose-postgres
        password: compose-postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format-sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    graphql:
        cors:
            allowed-origins: "*"
        schema:
            printer:
                enabled: true